version: "3.7"

networks: 
  backend_nw: 

services: 

  app: 
    build: 
      context: ../
      dockerfile: deployments/container/prodcomp_dockerfile
    container_name: prodcomp
    depends_on: 
      - mongodb
    links: 
      - mongodb
    networks: 
      - backend_nw
    ports: 
      - "11920:5000"

  mongo-express: 
    container_name: mongo-express
    depends_on: 
      - mongodb
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=ihavealongpassword
    image: mongo-express
    networks: 
      - backend_nw
    ports: 
      - "8985:8081"

  mongodb: 
    container_name: mongo-dev
    hostname: mongodb
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    image: mongo
    networks: 
      - backend_nw
    ports: 
      - "27017:27017"
